Fix definition of string_types in py27compat.py
Previously it would fail with:
  TypeError: set expected at most 1 arguments, got 2

Instead of using set, declare the tuple explicitly to avoid useless
memory copies.