BF: allow for import of keyring.util.properties but with a Deprecation warning if used
Unfortunately it is not a complete solution to #593 since there was likely
also a breakage in API of those properties since it would lead to e.g.

	(git)lena:~/proj/misc/keyrings.alt[main]git
	$> python -c 'import keyrings.alt.file'
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "/home/yoh/proj/misc/keyrings.alt/keyrings/alt/file.py", line 67, in <module>
		class EncryptedKeyring(Encrypted, Keyring):
	  File "/home/yoh/proj/misc/keyrings.alt/keyrings/alt/file.py", line 73, in EncryptedKeyring
		@properties.ClassProperty
	  File "/home/yoh/proj/misc/keyring/keyring/util/__init__.py", line 12, in __getattr__
		return getattr(_properties, a)
	AttributeError: module 'keyring._properties_compat' has no attribute 'ClassProperty'. Did you mean: 'classproperty'?